version: '3.8'

services:
  php:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: symfony_docker
    restart: on-failure
    ports:
      - "1234:80"
    volumes:
      - ./back/src:/var/www/symfony_docker
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./back/src:/var/www/symfony_docker
      - ./back/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  db:
    image: mariadb:10.8.2
    container_name: mariadb_docker
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'Changeme'
      MY_SQL_DATABASE: 'websocket'

  caddy:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'Changeme'
      MERCURE_SUBSCRIBER_JWT_KEY: 'Changeme'
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  db-data:  
  caddy_data:
  caddy_config:

networks:
    acpSymfony: